version: 2

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.7
  system_packages: true
  install:
    - requirements: docs/requirements.txt
    - method: pip
            path: .
