# Language setup
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Install pyinfra + test deps
install: 'pip install -e .[test]'

jobs:
  include:
    # Run the linting
    - stage: Lint
      script: flake8
    # Run the tests
    - stage: Test
      script: nosetests
