language: python

services:
    - docker

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install: 'pip install -e .[test]'

script:
  - flake8
  - pytest --cov -m"not vagrant"

after_success:
  - codecov
